version: 2.1
  
orbs:
  kube-orb: circleci/kubernetes@0.8.0

jobs:
  push-app:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nextler-api:$CIRCLE_SHA1 ./api
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nextler-api:$CIRCLE_SHA1    

  push-api:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nextler-app:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nextler-app:$CIRCLE_SHA1    

  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - kube-orb/install-kubectl
      - run:
          name: Update images
          command: |
            mkdir -p $HOME/.kube
            echo -n ${KUBECONFIG_ENCODED} | base64 --decode --ignore-garbage > $HOME/.kube/config
            kubectl set image deployment/app app="cmartel/nextler-app:${CIRCLE_SHA1}"
            kubectl set image deployment/api api="cmartel/nextler-api:${CIRCLE_SHA1}"

workflows:
  version: 2
  build-deploy:
    jobs:    
      - push-api:
          filters:
            branches:
              only: 
                - master
                - development
          context: DOCKERHUB
      - push-app:
          filters:
            branches:
              only: 
                - master
                - development        
          context: DOCKERHUB
      - deploy:
          filters:
            branches:
              only: master
            tags:
              only: /(\d|[1-9]\d*)\.(\d|[1-9]\d*)\.(\d|[1-9]\d*)/
          context: KUBESAIL
          requires:
            - push-api
            - push-app
