version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.8.0
jobs:
  push-app:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nextler-api:$CIRCLE_SHA1 ./api
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nextler-api:$CIRCLE_SHA1    

  push-api:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nextler-app:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nextler-app:$CIRCLE_SHA1    

  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout 
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG
      - kube-orb/install-kubectl
      - kube-orb/update-container-image:
          container-image-updates: 'app=$DOCKERHUB_USERNAME/nextler-api:$CIRCLE_SHA1'
          get-rollout-status: true
          record: true
          resource-name: deployment/app

workflows:
  version: 2
  build-deploy:
    jobs:    
      - push-api:
          context: DOCKERHUB
      - push-app:
          context: DOCKERHUB
      - deploy:
          context: KUBESAIL
          requires:
            - push-api
            - push-app
