version: 2
jobs:
  push:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nextler-app:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/nextler-app:$CIRCLE_SHA1    

workflows:
  version: 2
  build-deploy:
    jobs:    
      - push:
          context: DOCKERHUB

